### PR TITLE
Add drawing#mood_rating validation to ensure between 1-5;

### PR DESCRIPTION
**Pull request by mathildathompson**
## What this does
- [x] Update validation to ensure drawing#mood_rating value is between 1-5;
- [x] Add rake task `backfill_drawing_mood_rating_field` to backfill existing mood ratings to be between 1-5;
- [x] Do not affect any drawings that were uploaded after the merged changes on 24 Oct 2016 to limit the mood rating box from 1-5
- [x] Add output to rake task

## Screenshots
image

## Deploy Instructions
Rake tasks can be run by running:

```bundle exec rake backfill:mood_rating_field```

- Backfill existing drawing#mood_rating data to convert from range 1-10 -> 1-5;

### CODE REVIEW

**Comment by mathildathompson** [comment]
@krissy please can you review when you have a chance :-)

**Comment by steverabino** [comment]
Will require an update to https://github.com/empowerhack/DrawMyLife-Service/blob/master/spec/models/drawing_spec.rb#L28 to fix that broken test

**Review by krissy — COMMENTED** [review]
LGTM; just needs a rebase on master to fix the conflict :+1:

**Comment by steverabino** [comment]
Me and @krissy also spoke about whether the backfill rake task should be a database migration rather than a rake task - this would ensure that it is run when the code is updated on each environment, and also ensure that it is only ever run once on each environment

**Comment by stevesmith2609** [comment]
Although I'm happy to use the rake task (I've read some opinions that say data manipulation shouldn't be done in migrations), I am unable to run this rake task, what is the exact rake command that is required? I cannot find the task when I run `bundle exec rake --tasks`

**Review by steverabino — CHANGES_REQUESTED** [review]
Although I'm happy to use the rake task (I've read some opinions that say data manipulation shouldn't be done in migrations), I am unable to run this rake task, what is the exact rake command that is required? I cannot find the task when I run `bundle exec rake --tasks`

**Comment by steverabino** [comment]
@krissy @mathildathompson Can one or both of you take a peek and give a 👍  or 👎  on my commit made today? https://github.com/empowerhack/DrawMyLife-Service/pull/134/commits/f248c515bc75a2e3fe41d45fe52a42a1b8b1244e

**Review by steverabino — APPROVED** [review]

**Review by krissy — APPROVED** [review]
:dancing_men:

**Pull request merged**
