### PR TITLE
Mood ratings changed from 1-10 to 1-5

### PR DESCRIPTION
**Pull request by tanyapowell**
## What this does

Feedback from the Serbia pilot indicated that a rating of 1-10 was confusing. Rating changed to 1-5 for a short term solution 
#### Before

image
#### After

image

### CODE REVIEW

**Comment by EChesters** [comment]
Pulled down and checked. All works on my laptop and code looks good 👍
Feel free to merge.

**Comment by tanyapowell** [comment]
thanks @EChesters

**Comment by krissy** [comment]
Sorry for the late review on this! All looks good frontend-wise :) However, there's still a backend task to backfill the existing data so they're not rated outside of our new range, and also update the rails model validations accordingly so won't close the original issue just yet.

**Comment by tanyapowell** [comment]
Oh right...will need to re-open that issue. Maybe we need to agree as a team what's the best way to tackle opening and closing issues when there are frontend and backend tasks. Maybe use a checklist for subtasks and once every has been ticked off then the issue is closed?

**Pull request merged**
