### PR TITLE
[#53/72/74] Change hard-deletion of users to soft-deactivation, add decorators

### PR DESCRIPTION
**Pull request by krissy**
Addresses #53, #72 and #74 
# What this does

We no longer want to hard-delete users, just deactivate them, also securing the images they uploaded from being wiped. Also adds decorators for presentation logic going forward (#72).
## Features
- [x] Migration to add a `deleted_at` field to the user model
- [x] Override user.destroy method to update deleted_at field, sign user out and deactivate account, showing appropriate flash message
- [x] Update User Profile page to show Deactivated copy over Deleted
- [x] Add decorators via the [draper](https://github.com/drapergem/draper) gem (#72)
- [x] Set up [dotenv](https://github.com/bkeepers/dotenv) for managing development/test ENV vars + update README for copying config
- [x] Adds ENV var for support email ready to call with `Rails.application.config.support_email` whenever we need to show a support CTA. Currently set to `drawmylife@empowerhack.com`
## Local test instructions
- Checkout the branch
- Run `bundle install`
- Run `bundle exec rake db:migrate`
- As per the README update, copy the development env file: `cp .env.development.example .env`
- Start the server: `bundle exec rails s`
## Deployment instructions
- Add SUPPORT_EMAIL config var to heroku env vars
- Run migration
## Screenshots

Deleted user:

screen shot 2016-08-15 at 00 28 32

screen shot 2016-08-15 at 00 28 40

Deactivate copy:

screen shot 2016-08-15 at 00 43 27
evi

### CODE REVIEW

**Comment by krissy** [comment]
TODO: address rubocop failure before merge

**Comment by steverabino** [comment]
LGTM; you realise you're not actually using the support email anywhere, or is this for use later?

**Comment by krissy** [comment]
@stevesmith2609 Thank you! Yeah, I started building the support email code to use in Devise message for failed login. However, Devise currently makes it v complicated to use translations that have dynamic variables for their flash errors and was not worth the hack right now. :( The work had been done at least and I think the UI should definitely have a support link somewhere, so leaving it in.

**Comment by steverabino** [comment]
:+1:

**Pull request merged**
